### ISSUE TITLE
Mic stream performance

### ISSUE THREAD

**Issue by osolmaz** [fabricekwizera/deepspeech-rest-api#18]
`transcribe_mic_stream` performance on the client increases dramatically when we take these two lines out of the for loop. Is there a specific reason for them to be inside the loop?

Currently, `websocket.send()` is called for every frame, creating a lag on the client side which increases linearly with time.

https://github.com/fabricekwizera/deepspeech-rest-api/blob/0f0a106a88eb1334478d2339fccf0a0c5071a2e7/app/api/routes.py#L104-L105

**Comment by fabricekwizera** [comment]
@osolmaz If it doesn't break and returns the expected results, you can go with it. I will improve this piece of code in coming days, but not sure when.
