### ISSUE TITLE
Adding Postgres configuration in the documentation

### ISSUE THREAD

**Issue by rutsam** [fabricekwizera/deepspeech-rest-api#6]
Hi @fabricekwizera,
Can you add Postgres configurations in the documentation, as you need it to generate a token and if you can add Postgres in the docker compose that would be great

**Comment by fabricekwizera** [comment]
In the `.env` and `docker-compose.yaml` files, I added this line `DATABASE_URI=postgresql://forrest:gump@localhost/forrest` which is supposed to deal with Postgres. If you have it installed and it has a database with credentials, it is up to the user to replace the username, password, and database in that line...

**Comment by rutsam** [comment]
I was able to create the database however when I try to create a user it raises an error that no user table exit
**Environment I am using**

> All services are running in docker and here I am using 2 services in my docker-compose.yml
> services:
>    Deepspeech API
>    Postgres db


**Here are the logs from Deepspeech**

> TensorFlow: v2.3.0-6-g23ad988
> DeepSpeech: v0.9.3-0-gf2e9c85
> 2021-04-11 10:14:05.363899: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
> To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
> [2021-04-11 10:14:05 +0000] [6] [INFO] Goin' Fast @ http://0.0.0.0:5000
> [2021-04-11 10:14:05 +0000] [6] [INFO] Starting worker [6]
> [2021-04-11 10:14:34 +0000] [6] [ERROR] Exception occurred while handling uri: 'http://10.10.77.250:8000/users'
> Traceback (most recent call last):
>   File "/WORKDIR/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
>     self.dialect.do_execute(
>   File "/WORKDIR/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 691, in do_execute
>     cursor.execute(statement, parameters)
> psycopg2.errors.UndefinedTable: relation "users" does not exist
> LINE 2: FROM users

**And here is the logs from the DB**

> PostgreSQL Database directory appears to contain a database; Skipping initialization
> 
> 2021-04-11 10:14:01.990 UTC [1] LOG:  starting PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
> 2021-04-11 10:14:01.990 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
> 2021-04-11 10:14:01.991 UTC [1] LOG:  listening on IPv6 address "::", port 5432
> 2021-04-11 10:14:02.003 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
> 2021-04-11 10:14:02.026 UTC [25] LOG:  database system was shut down at 2021-04-11 10:13:08 UTC
> 2021-04-11 10:14:02.047 UTC [1] LOG:  database system is ready to accept connections
> 2021-04-11 10:14:34.779 UTC [33] ERROR:  relation "users" does not exist at character 209
> 2021-04-11 10:14:34.779 UTC [33] STATEMENT:  SELECT users.id AS users_id, users.username AS users_username, users.email AS users_email, users.password AS users_password, users.created_at AS users_created_at, users.modified_at AS users_modified_at 
>         FROM users 
>         WHERE users.username = 'forrestgump' 
>          LIMIT 1

**Comment by fabricekwizera** [comment]
@rutsam I believe that the issue you posted is related to Postgres and to know how to fix it requires to make Google searches on how to create users and database on that RDBMS... I am closing this issue.
